#!/usr/bin/env bash
# Build a self-contained local Swift package containing UniFFI client+broker
# wrappers and macOS/iOS XCFrameworks.
#
# Usage: packaging/swift/build_xcframework.sh <version>
# Output: packaging/swift/dist/StemMqttSwift-<version>.zip
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

version="${1:?usage: $0 <version>}"
dist="packaging/swift/dist"
work="packaging/swift/.build"
package_dir="$dist/StemMqttSwift"

rm -rf "$dist" "$work"
mkdir -p "$dist" "$work" "$package_dir/Sources/MqttClient" "$package_dir/Sources/MqttBroker"

rust_targets=(
    aarch64-apple-darwin
    x86_64-apple-darwin
    aarch64-apple-ios
    aarch64-apple-ios-sim
    x86_64-apple-ios
)
for target in "${rust_targets[@]}"; do
    rustup target add "$target" >/dev/null 2>&1 || true
done

build_xcframework() {
    crate="$1"
    cargo_package="$2"
    lib_name="$3"
    swift_name="$4"
    ffi_module="$5"

    echo "==> building ${crate} static libraries"
    for target in "${rust_targets[@]}"; do
        cargo build --release -p "$cargo_package" --target "$target"
    done

    crate_work="$work/$crate"
    mkdir -p "$crate_work/macos-universal" "$crate_work/ios-simulator-universal"
    lipo -create \
        "target/aarch64-apple-darwin/release/lib${lib_name}.a" \
        "target/x86_64-apple-darwin/release/lib${lib_name}.a" \
        -output "$crate_work/macos-universal/lib${lib_name}.a"
    lipo -create \
        "target/aarch64-apple-ios-sim/release/lib${lib_name}.a" \
        "target/x86_64-apple-ios/release/lib${lib_name}.a" \
        -output "$crate_work/ios-simulator-universal/lib${lib_name}.a"

    echo "==> generating ${swift_name} Swift bindings"
    generated="$crate_work/generated"
    ./scripts/generate-bindings.sh swift "$crate" "$generated"

    header="$generated/${lib_name}FFI.h"
    modulemap="$generated/${lib_name}FFI.modulemap"
    swift_source="$generated/${lib_name}.swift"
    for required in "$header" "$modulemap" "$swift_source"; do
        test -s "$required" || { echo "error: missing generated Swift file ${required}" >&2; exit 1; }
    done

    headers="$crate_work/headers"
    mkdir -p "$headers"
    cp "$header" "$headers/"
    cp "$modulemap" "$headers/module.modulemap"

    echo "==> assembling ${swift_name}FFI.xcframework"
    xcodebuild -create-xcframework \
        -library "$crate_work/macos-universal/lib${lib_name}.a" -headers "$headers" \
        -library "target/aarch64-apple-ios/release/lib${lib_name}.a" -headers "$headers" \
        -library "$crate_work/ios-simulator-universal/lib${lib_name}.a" -headers "$headers" \
        -output "$package_dir/${swift_name}FFI.xcframework"

    cp "$swift_source" "$package_dir/Sources/${swift_name}/${lib_name}.swift"

    # Broker bindings reference public types/functions generated by the client
    # crate. Keep wrappers in separate Swift modules (UniFFI emits duplicate
    # private helpers) and import the client module from broker source.
    if [ "$swift_name" = "MqttBroker" ]; then
        python3 - "$package_dir/Sources/${swift_name}/${lib_name}.swift" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
text = path.read_text()
needle = "import Foundation\n"
if "import MqttClient\n" not in text:
    text = text.replace(needle, needle + "import MqttClient\n", 1)
path.write_text(text)
PY
    fi

    # Ensure expected low-level module name survived xcodebuild packaging.
    rg -q "module ${ffi_module}" "$headers/module.modulemap" || {
        echo "error: ${ffi_module} missing from modulemap" >&2
        exit 1
    }
}

build_xcframework mqtt-client stem-mqtt-client mqtt_client MqttClient mqtt_clientFFI
build_xcframework mqtt-broker stem-mqtt-broker mqtt_broker MqttBroker mqtt_brokerFFI

cat > "$package_dir/Package.swift" <<'SWIFT'
// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "StemMqttSwift",
    platforms: [.macOS(.v11), .iOS(.v13)],
    products: [
        .library(name: "MqttClient", targets: ["MqttClient"]),
        .library(name: "MqttBroker", targets: ["MqttBroker"]),
    ],
    targets: [
        .binaryTarget(name: "MqttClientFFI", path: "MqttClientFFI.xcframework"),
        .target(name: "MqttClient", dependencies: ["MqttClientFFI"]),
        .binaryTarget(name: "MqttBrokerFFI", path: "MqttBrokerFFI.xcframework"),
        .target(name: "MqttBroker", dependencies: ["MqttBrokerFFI", "MqttClient"]),
    ]
)
SWIFT

cat > "$package_dir/README.md" <<EOF
# StemMqttSwift ${version}

Prebuilt UniFFI Swift package for stem-mqtt client and broker.

Add this extracted directory as a local Swift package, then import
\`MqttClient\` and/or \`MqttBroker\`. Includes macOS arm64/x86_64, iOS arm64,
and iOS Simulator arm64/x86_64 slices.
EOF

# Prove generated wrappers compile against packaged FFI modules.
(
    cd "$package_dir"
    swift build
)
rm -rf "$package_dir/.build" "$package_dir/.swiftpm"

zip_path="$dist/StemMqttSwift-${version}.zip"
(
    cd "$dist"
    zip -qr "$(basename "$zip_path")" StemMqttSwift
)
unzip -t "$zip_path" >/dev/null

echo "done: $zip_path"
