// swift-tools-version:5.9
// Auto-generated by packaging/swift/update_manifest.sh for v0.2.1 — do not
// edit by hand; re-run the script (or the release workflow) instead.
import PackageDescription

let package = Package(
    name: "MqttClient",
    platforms: [.macOS(.v11), .iOS(.v13)],
    products: [
        .library(name: "MqttClient", targets: ["MqttClient"]),
    ],
    targets: [
        .binaryTarget(
            name: "MqttClient",
            url: "https://github.com/sorinirimies/stem-mqtt/releases/download/v0.2.1/MqttClient-0.2.1.xcframework.zip",
            checksum: "6704f982d92917112686fd519048ee747808503b771a51e4e4cb059b8545a69d"
        ),
    ]
)
