// swift-tools-version:5.9
// Auto-generated by packaging/swift/update_manifest.sh for v0.2.0 — do not
// edit by hand; re-run the script (or the release workflow) instead.
import PackageDescription

let package = Package(
    name: "MqttClient",
    platforms: [.macOS(.v11), .iOS(.v13)],
    products: [
        .library(name: "MqttClient", targets: ["MqttClient"]),
    ],
    targets: [
        .binaryTarget(
            name: "MqttClient",
            url: "https://github.com/sorinirimies/stem-mqtt/releases/download/v0.2.0/MqttClient-0.2.0.xcframework.zip",
            checksum: "a32293f9bb4c3a2f1346d97129c84fa080425d3cd59def397a4d3eea3d2bcbc4"
        ),
    ]
)
