#!/usr/bin/env bash
# Updates packaging/swift/Package.swift to point at the XCFramework zip
# attached to a given GitHub release, with its checksum, so Swift Package
# Manager can resolve it as a `.binaryTarget(url:checksum:)`.
#
# SPM has no external package registry the way npm/PyPI do — the git
# repository (this repo, referenced by tag) *is* the "registry" entry.
# Consumers add this repo as a Swift Package dependency directly.
#
# Usage: packaging/swift/update_manifest.sh <tag>
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

tag="${1:?usage: $0 <tag>}"
version="${tag#v}"
zip_name="MqttClient-${version}.xcframework.zip"
zip_path="packaging/swift/dist/${zip_name}"
url="https://github.com/sorinirimies/stem-mqtt/releases/download/${tag}/${zip_name}"

if [ ! -f "$zip_path" ]; then
    echo "error: ${zip_path} not found — run build_xcframework.sh first" >&2
    exit 1
fi

checksum="$(swift package compute-checksum "$zip_path")"

cat > packaging/swift/Package.swift <<EOF
// swift-tools-version:5.9
// Auto-generated by packaging/swift/update_manifest.sh for ${tag} — do not
// edit by hand; re-run the script (or the release workflow) instead.
import PackageDescription

let package = Package(
    name: "MqttClient",
    platforms: [.macOS(.v11), .iOS(.v13)],
    products: [
        .library(name: "MqttClient", targets: ["MqttClient"]),
    ],
    targets: [
        .binaryTarget(
            name: "MqttClient",
            url: "${url}",
            checksum: "${checksum}"
        ),
    ]
)
EOF

echo "updated packaging/swift/Package.swift -> ${tag} (checksum ${checksum})"
